#!/bin/sh

set -eu

http_secret=`leader-get http-secret`
if [ -n "$http_secret" ]; then
	exit 0
fi

http_secret=`dd if=/dev/urandom count=1 bs=24 status=none | base64 -w0`
leader-set "http-secret=$http_secret"
