#!/usr/bin/python3

from charmhelpers.contrib.charmsupport.nrpe import NRPE
from charmhelpers.core import hookenv


HTTP_LISTEN_PORT = 5000


def update_nrpe_config():
    """Update the NRPE configuration for the given service."""
    hookenv.log("updating NRPE checks")
    service = hookenv.metadata()['name']
    nrpe = NRPE()
    nrpe.add_check(
        shortname=service,
        description='Check {} running'.format(service),
        check_cmd='check_http -w 2 -c 10 -I {} -p {} -u /'.format(
            hookenv.unit_private_ip(),
            HTTP_LISTEN_PORT,
        )
    )
    nrpe.write()


if __name__ == '__main__':
    hookenv.log('nrpe-relation-changed')
    update_nrpe_config()
