#!/bin/sh

set -eu

juju-log 'Installing charm dependencies'
apt-get install --no-install-recommends -y python3-yaml

juju-log 'Installing docker registry'
apt-get install --no-install-recommends -y docker-registry

application-version-set `dpkg -s docker-registry | sed -n -e 's/Version: \(.*\)$/\1/p'`
