#!/usr/local/sbin/charm-env python3

import sys
from subprocess import CalledProcessError

from charmhelpers.core import hookenv
from charms.reactive import is_flag_set
from charms.layer.docker_registry import start_registry


def fail(msg):
    hookenv.action_fail(msg)
    sys.exit()


if not is_flag_set('charm.docker-registry.configured'):
    fail('Docker Registry charm is not yet ready.')

name = hookenv.action_get('name')

try:
    start_registry(name=name)
except CalledProcessError:
    fail('Failed to start container.')
else:
    hookenv.action_set({'outcome': 'success'})
