name: Run tests with Tox

on: [pull_request]

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@7aa0f7a606f182bd03a7adb28e0d710216101ca5 # main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@6ee58c37d404effad4598ce7b523dbaf0cb99285 # main
    with:
      python: "['3.10', '3.12']"
    needs:
      - call-inclusive-naming-check 

  integration-tests:
    name: Integration test with LXD
    runs-on: ubuntu-latest
    needs:
      - lint-unit
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@ea90ed489690bf3b1c1fcca6ac5f9edab70aecb0 # main
        with:
          provider: lxd
          juju-channel: 3/stable
          charmcraft-channel: ${{ steps.charmcraft.outputs.channel }}
      - name: Run integration test
        run: tox -e integration
